consumes:
- application/json
definitions:
  Pet:
    properties:
      category:
        $ref: '#/definitions/category'
      id:
        type: string
      name:
        type: string
      photoUrls:
        $ref: '#/definitions/photoUrls'
      status:
        type: string
      tags:
        $ref: '#/definitions/tags'
    required:
    - photoUrls
    - name
    - id
    - categoryddd
    - status
    - tags
    type: object
  category:
    properties:
      id:
        type: string
      name:
        type: string
    required:
    - name
    - id
    type: object
  photoUrls:
    properties:
      photoUrl:
        type: string
    required:
    - photoUrl
    type: object
  tag:
    properties:
      id:
        type: string
      name:
        type: string
    required:
    - name
    - id
    type: object
  tags:
    properties:
      tag:
        items:
          $ref: '#/definitions/tag'
          uniqueItems: false
        type: array
    type: object
host: localhost:8080
info:
  contact:
    name: Swagger API Team
  description: BW Cloud PetStore Sample
  license:
    name: MIT
  termsOfService: http://swagger.io/terms/
  title: BW Cloud PetStore Sample
  version: "1.0"
  x-lastModified: Jan 17, 2019 10:46AM PST
paths:
  /pet/{petId}:
    delete:
      consumes:
      - application/json
      description: ""
      operationId: deletepet
      parameters:
      - description: ""
        in: path
        name: petId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: a string to be returned
          schema:
            type: string
    get:
      consumes:
      - application/json
      description: ""
      operationId: getpet
      parameters:
      - description: ""
        in: path
        name: petId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: a Pet to be returned
          examples:
            application/json:
              category:
                id: "1"
                name: Domesticated pets
              id: "2"
              name: Dog2
              photoUrls:
                photoUrl: http://s5.favim.com/orig/69/adorable-cute-dog-photography-Favim.com-659715.jpg
              status: Available
              tags:
                tag:
                - id: "2"
                  name: Dogs
          schema:
            $ref: '#/definitions/Pet'
    post:
      consumes:
      - application/json
      description: ""
      operationId: postpet
      parameters:
      - default: ads
        description: ""
        format: ""
        in: query
        name: dasasd
        required: false
        type: string
      - description: ""
        format: ""
        in: path
        name: petId
        required: true
        type: string
      - description: ""
        in: body
        name: ""
        schema:
          $ref: '#/definitions/Pet'
      produces:
      - application/json
      responses:
        "200":
          description: a Pet to be returned
          examples:
            application/json:
              category:
                id: "1"
                name: Domesticated pets
              id: "2"
              name: Dog2
              photoUrls:
                photoUrl: http://s5.favim.com/orig/69/adorable-cute-dog-photography-Favim.com-659715.jpg
              status: Available
              tags:
                tag:
                - id: "2"
                  name: Dogs
          schema:
            $ref: '#/definitions/Pet'
    put:
      consumes:
      - application/json
      description: ""
      operationId: putpet
      parameters:
      - description: ""
        in: body
        name: ""
        required: true
        schema:
          $ref: '#/definitions/Pet'
      - description: ""
        in: path
        name: petId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: a Pet to be returned
          examples:
            application/json:
              category:
                id: "1"
                name: Domesticated pets
              id: "6"
              name: Dog6
              photoUrls:
                photoUrl: http://s5.favim.com/orig/69/adorable-cute-dog-photography-Favim.com-659715.jpg
              status: Available
              tags:
                tag:
                - id: "6"
                  name: Dogs
          schema:
            $ref: '#/definitions/Pet'
produces:
- application/json
schemes:
- http
swagger: "2.0"
